#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.11
# In conjunction with Tcl version 8.6
#    Mar 13, 2018 09:31:39 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
def set_Tk_var():
    global che39
    che39 = StringVar()
    global che40
    che40 = StringVar()
    global che45
    che45 = StringVar()
    global che46
    che46 = StringVar()
    global che38
    che38 = StringVar()
    global che41
    che41 = StringVar()
    global che42
    che42 = StringVar()
    global che44
    che44 = StringVar()
    global che48
    che48 = StringVar()
    global che47
    che47 = StringVar()



def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import unknown
    unknown.vp_start_gui()

